defmodule WebUI.Renderer do
  @moduledoc """
  Minimal HTML renderer package used by Ash UI in external renderer mode.
  """

  @spec render(map(), keyword()) :: {:ok, String.t()}
  def render(canonical_iur, opts \\ []) when is_map(canonical_iur) do
    {:ok, generate_html(canonical_iur, opts)}
  end

  defp generate_html(%{"type" => "screen"} = iur, opts) do
    seo_enabled = Keyword.get(opts, :seo_enabled, true)
    elm_enabled = Keyword.get(opts, :elm_enabled, false)
    elm_module = Keyword.get(opts, :elm_module, "Main")
    assets_url = Keyword.get(opts, :assets_url, "/assets")
    include_css = Keyword.get(opts, :include_css, true)
    include_js = Keyword.get(opts, :include_js, true)
    fingerprinted = Keyword.get(opts, :asset_fingerprinting, true)
    title = Keyword.get(opts, :title, Map.get(iur, "name", "AshUI Screen"))
    description = Keyword.get(opts, :description, "Generated by AshUI renderer package")

    keywords =
      iur
      |> Map.get("metadata", %{})
      |> Map.get("keywords", [])
      |> Enum.join(", ")

    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      #{if seo_enabled, do: "<title>#{title}</title><meta name=\"description\" content=\"#{description}\">", else: ""}
      #{if seo_enabled and keywords != "", do: "<meta name=\"keywords\" content=\"#{keywords}\">", else: ""}
      #{if include_css, do: asset_tag(:css, assets_url, "app.css", fingerprinted), else: ""}
      #{if include_js, do: asset_tag(:js, assets_url, "app.js", fingerprinted), else: ""}
      #{if elm_enabled, do: "<script src=\"#{assets_url}/#{String.downcase(elm_module)}.js\"></script>", else: ""}
    </head>
    <body class="ash-screen ash-screen-#{iur["name"]}" data-screen-id="#{iur["id"]}">
      #{generate_children(iur["children"])}
      #{if elm_enabled, do: generate_elm_mount(elm_module, extract_elm_ports(iur)), else: ""}
    </body>
    </html>
    """
  end

  defp generate_html(%{"type" => type, "id" => id} = iur, _opts) do
    """
    <div class="ash-widget ash-widget-#{type}" data-widget-id="#{id}">
      #{generate_children(iur["children"])}
    </div>
    """
  end

  defp generate_children(nil), do: ""
  defp generate_children([]), do: ""
  defp generate_children(children), do: Enum.map_join(children, &generate_html(&1, []))

  defp generate_elm_mount(elm_module, ports) do
    flags =
      if map_size(ports) > 0 do
        ",\n    flags: #{encode_ports_json(ports)}"
      else
        ""
      end

    """
    <div id="elm-app"></div>
    <script>
      Elm.#{elm_module}.init({ node: document.getElementById("elm-app")#{flags} });
    </script>
    """
  end

  defp extract_elm_ports(iur) do
    iur
    |> Map.get("bindings", [])
    |> Enum.filter(fn binding -> Map.get(binding, "type") in ["bidirectional", "collection"] end)
    |> Enum.map(fn binding ->
      target = Map.get(binding, "target")
      source = Map.get(binding, "source", %{})
      {target, Map.get(source, "default")}
    end)
    |> Map.new()
  end

  defp encode_ports_json(ports) do
    entries =
      Enum.map_join(ports, ", ", fn {key, value} ->
        "\"#{key}\": #{encode_json_value(value)}"
      end)

    "{#{entries}}"
  end

  defp encode_json_value(value) when is_binary(value), do: "\"#{value}\""
  defp encode_json_value(value) when is_boolean(value) or is_number(value), do: to_string(value)
  defp encode_json_value(nil), do: "null"
  defp encode_json_value(value), do: "\"#{inspect(value)}\""

  defp asset_tag(kind, assets_url, file, fingerprinted) do
    fingerprint = if fingerprinted, do: "?v=#{:erlang.phash2(file)}", else: ""

    case kind do
      :css -> "<link rel=\"stylesheet\" href=\"#{assets_url}/#{file}#{fingerprint}\">"
      :js -> "<script src=\"#{assets_url}/#{file}#{fingerprint}\"></script>"
    end
  end
end
