defmodule AshUI.Resources.Validations.UnifiedDSL do
  @moduledoc """
  Validates persisted `unified_dsl` payloads before they are stored on screens.

  Screen records in this repo must store a Phase 10 persisted `UnifiedUi.Dsl`
  authoring document generated by `AshUI.Authoring`.
  """

  use Ash.Resource.Validation

  alias Ash.Error.Changes.InvalidAttribute
  alias Ash.Subject
  alias AshUI.Authoring.Document

  @doc false
  @impl true
  def supports(_opts), do: [Ash.Changeset, Ash.ActionInput]

  @doc false
  @impl true
  def validate(subject, _opts, _context) do
    dsl = Subject.get_attribute(subject, :unified_dsl)

    with :ok <- validate_map(dsl) do
      if Document.authoring_document?(dsl) do
        case Document.validate_write(dsl) do
          :ok -> :ok
          {:error, message} -> invalid_dsl(dsl, message)
        end
      else
        invalid_dsl(dsl, "must declare the Phase 10 ash_ui unified_ui document format")
      end
    end
  end

  defp validate_map(dsl) when is_map(dsl), do: :ok

  defp validate_map(dsl) do
    invalid_dsl(dsl, "must be a map")
  end

  defp invalid_dsl(value, message) do
    {:error, InvalidAttribute.exception(field: :unified_dsl, value: value, message: message)}
  end
end
